Added Kodi Addon-News and developers to Team
mediathekview/MediathekViewDE pull request #32
Opened 2018-01-10 12:34 UTC by Nicklas2751

Ich habe eine News über das Kodi Add-On verfasst und @tuxpoldo & @domschl in die Team-Seite aufgenommen. Angaben wie GitHub Profil, Webseite und Profilbild habe ich von GitHub übernommen bzw. im Falle des Profilbildes das wie üblich direkt das von GitHub eingebunden.

@alex1702 @domschl @tuxpoldo Passt das so für euch?

2018-01-10 14:22 UTC, domschl approved these changes
Ok.

2018-01-10 15:04 UTC, tuxpoldo requested changes
Hallo Nicklas,
könnten wir die Screenshots kodiaddon002 bis kodiaddon005 ersetzen? Die Deutsche Version funktioniert nämlich jetzt. kodiaddon006 würde ich rausnehmen, da der ziemlich hässlich ist. Ich schicke Dir die neuen Shots per riot.im

2018-01-10 18:53 UTC, tuxpoldo reviewed
Perfekt!

2018-01-10 18:54 UTC, tuxpoldo approved these changes

2018-01-11 04:38 UTC, alex1702 approved these changes

2018-01-11 04:39 UTC, merged