Created news for Zapp
mediathekview/MediathekViewDE pull request #42
Opened 2019-07-11 06:49 UTC by Nicklas2751

2019-07-11 13:47 UTC, bagbag approved these changes
Sieht gut aus

2019-07-11 18:18 UTC, cemrich requested changes
ein Paar Kleinigkeiten

2019-07-11 18:18 UTC, cemrich commented on content/news/zapp.md
> +Die Entwicklerin [cemrich](https://github.com/cemrich/) hat sich entschlossen sich dem MediathekView Team anzuschließen und ihre Andorid App [Zapp](https://f-droid.org/de/packages/de.christinecoenen.
"sich entschlossen, sich dem"

2019-07-11 18:18 UTC, cemrich commented on content/news/zapp.md
> +Zapp ist eine Android App mit der die aktuellen Livestreams der öffentlich-rechtlichen geschaut und einzelne Sendungen heruntergeladen werden können. Zapp nutzt hierbei unter anderem die MediathekVie
"der Öffentlich-Rechtlichen"
oder "der öffentlich-rechtlichen Sender"

2019-07-11 18:18 UTC, cemrich commented on content/news/zapp.md
> +Zapp ist eine Android App mit der die aktuellen Livestreams der öffentlich-rechtlichen geschaut und einzelne Sendungen heruntergeladen werden können. Zapp nutzt hierbei unter anderem die MediathekVie
"unter anderem die Datenbasis von MediathekView"

2019-07-11 18:18 UTC, cemrich commented on content/news/zapp.md
> +Zapp ist eine Android App mit der die aktuellen Livestreams der öffentlich-rechtlichen geschaut und einzelne Sendungen heruntergeladen werden können. Zapp nutzt hierbei unter anderem die MediathekVie
"Zapp ist eine Android-App, mit der die"

2019-07-11 18:39 UTC, alex1702 commented
Muhaha vielen dank ^^

2019-07-12 12:13 UTC, cemrich approved these changes

2019-07-13 14:53 UTC, merged